# Generated by Django 6.1 on 2026-09-09 07:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('education_levels', models.CharField(choices=[('sd', 'Elementary School'), ('smp', 'Junior High School'), ('sma', 'Senior High School'), ('kuliah', 'College')], max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('started_at', models.CharField(max_length=4)),
                ('ended_at', models.CharField(default='Sekarang', max_length=20)),
            ],
        ),
    ]
